begin;

-- ============================================================================
-- PRESUPUESTOS CON SNAPSHOT HISTÓRICO DE CONCEPTOS
--
-- Esta migración crea:
--   1. public.presupuestos
--   2. public.presupuesto_programas
--   3. public.presupuesto_partidas
--
-- Decisiones principales:
--   - Un presupuesto pertenece a un club y puede abarcar varios programas.
--   - Las partidas pertenecen al presupuesto completo, no a cada programa.
--   - Solo existe una partida oficial por concepto y presupuesto.
--   - Mientras el presupuesto está en borrador se consulta el catálogo actual
--     de public.conceptos.
--   - Al cerrar, nombre, naturaleza y subvencionabilidad se copian a las
--     partidas dentro de la misma transacción y quedan congelados.
--   - concepto_id se conserva para comparar posteriormente la ejecución con
--     public.contabilidad.concepto_id.
--
-- Esta migración no modifica Storage ni utiliza presupuesto_previsto como
-- detalle presupuestario.
-- ============================================================================


-- ============================================================================
-- 1. GUARDS PREVIOS
-- ============================================================================

do $presupuestos_preflight$
declare
  v_tabla text;
begin
  -- Las tablas de las que depende el modelo deben existir antes de continuar.
  foreach v_tabla in array array[
    'clubes',
    'programas',
    'conceptos',
    'subvenciones',
    'subvencion_programas'
  ]
  loop
    if to_regclass(format('public.%I', v_tabla)) is null then
      raise exception
        'Migración de Presupuestos abortada: falta la tabla public.%.',
        v_tabla;
    end if;
  end loop;

  -- La presencia de cualquiera de las tablas nuevas indicaría una instalación
  -- parcial o un cambio no auditado. En ese caso no se sobrescribe nada.
  foreach v_tabla in array array[
    'presupuestos',
    'presupuesto_programas',
    'presupuesto_partidas'
  ]
  loop
    if to_regclass(format('public.%I', v_tabla)) is not null then
      raise exception
        'Migración de Presupuestos abortada: public.% ya existe.',
        v_tabla;
    end if;
  end loop;

  -- Verifica el modelo de autorización desplegado por la Migración 1.
  if to_regprocedure('public.can_access_club(bigint)') is null then
    raise exception
      'Migración abortada: no existe public.can_access_club(bigint).';
  end if;

  if to_regprocedure('public.can_edit_club(bigint)') is null then
    raise exception
      'Migración abortada: no existe public.can_edit_club(bigint).';
  end if;

  -- El cierre y el snapshot solo reconocen las dos naturalezas auditadas.
  if exists (
    select 1
    from public.conceptos as c
    where c.naturaleza is null
       or c.naturaleza not in ('gasto', 'ingreso')
  ) then
    raise exception
      'Migración abortada: existen conceptos con naturaleza desconocida.';
  end if;

  -- Los programas existentes deben usar las familias soportadas por el nuevo
  -- modelo para que la comparación estructurada sea segura.
  if exists (
    select 1
    from public.programas as p
    where p.tipo_programa is null
       or p.tipo_programa not in (
         'clubes',
         'eventos',
         'eedd_ctd_discapacidad'
       )
  ) then
    raise exception
      'Migración abortada: existen programas con tipo_programa desconocido.';
  end if;
end;
$presupuestos_preflight$;


-- ============================================================================
-- 2. CLAVES ÚNICAS COMPUESTAS PARA EL AISLAMIENTO ESTRUCTURAL POR CLUB
--
-- Las PK existentes garantizan la unicidad del identificador. Estas claves
-- adicionales permiten que las nuevas FKs comprueben simultáneamente el ID y
-- el club, sin confiar solo en RLS ni en el frontend.
-- ============================================================================

alter table public.programas
  add constraint programas_id_programa_club_id_key
  unique (id_programa, club_id);

alter table public.conceptos
  add constraint conceptos_id_concepto_club_id_key
  unique (id_concepto, club_id);

alter table public.subvenciones
  add constraint subvenciones_id_subvencion_club_id_key
  unique (id_subvencion, club_id);


-- ============================================================================
-- 3. CABECERAS DE PRESUPUESTO
-- ============================================================================

create table public.presupuestos (
  -- Identificador técnico del presupuesto.
  id_presupuesto bigint generated by default as identity primary key,

  -- Agrupa las distintas versiones de un mismo presupuesto lógico.
  serie_id uuid not null default gen_random_uuid(),

  -- Club propietario y ámbito de aislamiento RLS.
  club_id bigint not null,

  -- Convocatoria o expediente opcional. NULL identifica un presupuesto
  -- interno independiente de una subvención.
  subvencion_id bigint,

  nombre text not null,

  -- Familia funcional común con programas.tipo_programa.
  tipo_programa text not null,

  -- Clasificación estructurada para EEDD, CTD o EEDD discapacidad.
  subtipo_programa text,

  -- Forma de expresar el periodo: ejercicio, temporada o evento.
  periodo_tipo text not null,

  anio_inicio integer not null,
  anio_fin integer not null,
  fecha_inicio date not null,
  fecha_fin date not null,

  -- Número de versión dentro de serie_id.
  version integer not null default 1,

  -- La primera versión del módulo solo utiliza borrador y cerrado.
  estado text not null default 'borrador',

  observaciones text,

  -- Se conserva el presupuesto si el usuario creador se elimina.
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  cerrado_at timestamptz,

  constraint presupuestos_club_id_fkey
    foreign key (club_id)
    references public.clubes (id_club)
    on delete restrict,

  -- Impide estructuralmente relacionar una subvención de otro club.
  constraint presupuestos_subvencion_club_fkey
    foreign key (subvencion_id, club_id)
    references public.subvenciones (id_subvencion, club_id)
    on delete restrict,

  constraint presupuestos_created_by_fkey
    foreign key (created_by)
    references auth.users (id)
    on delete set null,

  constraint presupuestos_tipo_programa_check
    check (
      tipo_programa in ('clubes', 'eventos', 'eedd_ctd_discapacidad')
    ),

  -- No se admite NULL transitorio para EEDD/CTD porque la tabla es nueva y no
  -- hay presupuestos históricos que migrar.
  constraint presupuestos_subtipo_programa_check
    check (
      (
        tipo_programa in ('clubes', 'eventos')
        and subtipo_programa is null
      )
      or
      (
        tipo_programa = 'eedd_ctd_discapacidad'
        and subtipo_programa is not null
        and subtipo_programa in ('eedd', 'ctd', 'eedd_discapacidad')
      )
    ),

  constraint presupuestos_periodo_tipo_check
    check (periodo_tipo in ('ejercicio', 'temporada', 'evento')),

  constraint presupuestos_anios_check
    check (anio_fin >= anio_inicio),

  constraint presupuestos_fechas_check
    check (fecha_fin >= fecha_inicio),

  -- Las fechas exactas deben coincidir con el intervalo de años declarado.
  constraint presupuestos_fechas_anios_check
    check (
      extract(year from fecha_inicio)::integer = anio_inicio
      and extract(year from fecha_fin)::integer = anio_fin
    ),

  constraint presupuestos_version_check
    check (version > 0),

  constraint presupuestos_estado_check
    check (estado in ('borrador', 'cerrado')),

  -- cerrado_at solo puede existir cuando la cabecera está cerrada.
  constraint presupuestos_cierre_check
    check (
      (estado = 'borrador' and cerrado_at is null)
      or
      (estado = 'cerrado' and cerrado_at is not null)
    ),

  -- Esta clave soporta las FKs compuestas de las tablas hijas.
  constraint presupuestos_id_club_key
    unique (id_presupuesto, club_id),

  constraint presupuestos_serie_version_key
    unique (club_id, serie_id, version)
);


-- ============================================================================
-- 4. PROGRAMAS CONTABLES INCLUIDOS EN CADA PRESUPUESTO
-- ============================================================================

create table public.presupuesto_programas (
  id_presupuesto_programa bigint generated by default as identity primary key,
  club_id bigint not null,
  presupuesto_id bigint not null,
  programa_id bigint not null,
  created_at timestamptz not null default now(),

  constraint presupuesto_programas_presupuesto_club_fkey
    foreign key (presupuesto_id, club_id)
    references public.presupuestos (id_presupuesto, club_id)
    on delete restrict,

  constraint presupuesto_programas_programa_club_fkey
    foreign key (programa_id, club_id)
    references public.programas (id_programa, club_id)
    on delete restrict,

  constraint presupuesto_programas_presupuesto_programa_key
    unique (presupuesto_id, programa_id)
);


-- ============================================================================
-- 5. PARTIDAS OFICIALES Y SNAPSHOT HISTÓRICO
--
-- Los tres campos snapshot son administrados por el proceso de cierre:
--   - En borrador pueden permanecer NULL y se usa public.conceptos.
--   - Al cerrar se sobrescriben con el catálogo vigente en ese instante.
--   - En informes cerrados deben usarse los snapshots.
-- ============================================================================

create table public.presupuesto_partidas (
  id_partida bigint generated by default as identity primary key,
  club_id bigint not null,
  presupuesto_id bigint not null,
  concepto_id bigint not null,
  descripcion text,
  importe_presupuestado numeric(14, 2) not null,
  orden integer not null default 0,

  -- Interpretación histórica congelada al cerrar el presupuesto.
  concepto_nombre_snapshot text,
  naturaleza_snapshot text,
  subvencionabilidad_snapshot text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint presupuesto_partidas_presupuesto_club_fkey
    foreign key (presupuesto_id, club_id)
    references public.presupuestos (id_presupuesto, club_id)
    on delete restrict,

  constraint presupuesto_partidas_concepto_club_fkey
    foreign key (concepto_id, club_id)
    references public.conceptos (id_concepto, club_id)
    on delete restrict,

  constraint presupuesto_partidas_importe_check
    check (importe_presupuestado >= 0),

  constraint presupuesto_partidas_orden_check
    check (orden >= 0),

  constraint presupuesto_partidas_naturaleza_snapshot_check
    check (
      naturaleza_snapshot is null
      or naturaleza_snapshot in ('gasto', 'ingreso')
    ),

  constraint presupuesto_partidas_subvencionabilidad_snapshot_check
    check (
      subvencionabilidad_snapshot is null
      or subvencionabilidad_snapshot in (
        'subvencionable',
        'no_subvencionable',
        'condicionada'
      )
    ),

  -- En v1 existe una sola partida oficial por concepto. En el futuro puede
  -- añadirse presupuesto_partida_detalles dependiendo de id_partida sin
  -- alterar este modelo principal.
  constraint presupuesto_partidas_presupuesto_concepto_key
    unique (presupuesto_id, concepto_id)
);


-- ============================================================================
-- 6. ÍNDICES
-- ============================================================================

create index presupuestos_club_periodo_idx
  on public.presupuestos (club_id, anio_inicio, anio_fin);

create index presupuestos_club_estado_idx
  on public.presupuestos (club_id, estado);

create index presupuestos_subvencion_idx
  on public.presupuestos (subvencion_id)
  where subvencion_id is not null;

create index presupuesto_programas_programa_idx
  on public.presupuesto_programas (programa_id, presupuesto_id);

create index presupuesto_partidas_concepto_idx
  on public.presupuesto_partidas (concepto_id, presupuesto_id);

create index presupuesto_partidas_orden_idx
  on public.presupuesto_partidas (presupuesto_id, orden, id_partida);


-- ============================================================================
-- 7. FUNCIÓN AUXILIAR DE INMUTABILIDAD DE HIJOS
--
-- FOR UPDATE coordina cambios concurrentes. Una operación sobre hijos bloquea
-- la cabecera y un cierre concurrente espera. Si el cierre gana el bloqueo,
-- la operación posterior ve el estado cerrado y se rechaza.
-- ============================================================================

create function public.assert_presupuesto_borrador(
  p_presupuesto_id bigint,
  p_club_id bigint,
  p_operacion text
)
returns void
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_estado text;
begin
  select p.estado
  into v_estado
  from public.presupuestos as p
  where p.id_presupuesto = p_presupuesto_id
    and p.club_id = p_club_id
  for update;

  if not found then
    raise exception
      'No existe el presupuesto % en el club % al intentar %.',
      p_presupuesto_id,
      p_club_id,
      p_operacion;
  end if;

  if v_estado <> 'borrador' then
    raise exception
      'No se puede %: el presupuesto % está cerrado.',
      p_operacion,
      p_presupuesto_id;
  end if;
end;
$function$;

revoke all
on function public.assert_presupuesto_borrador(bigint, bigint, text)
from public;


-- ============================================================================
-- 8. INMUTABILIDAD DE PRESUPUESTO_PROGRAMAS
--
-- INSERT comprueba NEW, DELETE comprueba OLD y UPDATE comprueba ambos. Esto
-- impide mover una relación desde un presupuesto cerrado a uno abierto.
-- ============================================================================

create function public.enforce_presupuesto_programas_borrador()
returns trigger
language plpgsql
security definer
set search_path = ''
as $function$
begin
  if tg_op = 'INSERT' then
    perform public.assert_presupuesto_borrador(
      new.presupuesto_id,
      new.club_id,
      'insertar una relación presupuesto-programa'
    );
    return new;
  end if;

  if tg_op = 'DELETE' then
    perform public.assert_presupuesto_borrador(
      old.presupuesto_id,
      old.club_id,
      'eliminar una relación presupuesto-programa'
    );
    return old;
  end if;

  perform public.assert_presupuesto_borrador(
    old.presupuesto_id,
    old.club_id,
    'modificar la relación presupuesto-programa de origen'
  );

  perform public.assert_presupuesto_borrador(
    new.presupuesto_id,
    new.club_id,
    'modificar la relación presupuesto-programa de destino'
  );

  return new;
end;
$function$;

revoke all
on function public.enforce_presupuesto_programas_borrador()
from public;


-- ============================================================================
-- 9. COMPATIBILIDAD ENTRE PRESUPUESTO Y PROGRAMA
-- ============================================================================

create function public.validate_presupuesto_programa()
returns trigger
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_presupuesto public.presupuestos%rowtype;
  v_programa public.programas%rowtype;
begin
  select p.*
  into v_presupuesto
  from public.presupuestos as p
  where p.id_presupuesto = new.presupuesto_id
    and p.club_id = new.club_id;

  if not found then
    raise exception
      'No existe el presupuesto % en el club indicado.',
      new.presupuesto_id;
  end if;

  select p.*
  into v_programa
  from public.programas as p
  where p.id_programa = new.programa_id
    and p.club_id = new.club_id;

  if not found then
    raise exception
      'El programa % no existe o no pertenece al club del presupuesto.',
      new.programa_id;
  end if;

  if v_programa.club_id <> v_presupuesto.club_id then
    raise exception
      'El programa % y el presupuesto % pertenecen a clubes distintos.',
      new.programa_id,
      new.presupuesto_id;
  end if;

  if v_programa.tipo_programa
     is distinct from v_presupuesto.tipo_programa
  then
    raise exception
      'Programa incompatible: tipo del programa = %, tipo del presupuesto = %.',
      v_programa.tipo_programa,
      v_presupuesto.tipo_programa;
  end if;

  if v_programa.anio is null
     or v_programa.anio < v_presupuesto.anio_inicio
     or v_programa.anio > v_presupuesto.anio_fin
  then
    raise exception
      'Programa incompatible: año del programa = %, periodo del presupuesto = %-%.',
      coalesce(v_programa.anio::text, 'NULL'),
      v_presupuesto.anio_inicio,
      v_presupuesto.anio_fin;
  end if;

  -- Cuando hay subvención, el programa debe formar parte de la convocatoria.
  if v_presupuesto.subvencion_id is not null
     and not exists (
       select 1
       from public.subvencion_programas as sp
       where sp.subvencion_id = v_presupuesto.subvencion_id
         and sp.programa_id = new.programa_id
         and sp.club_id = new.club_id
     )
  then
    raise exception
      'El programa % no está vinculado a la subvención % del presupuesto.',
      new.programa_id,
      v_presupuesto.subvencion_id;
  end if;

  return new;
end;
$function$;

revoke all
on function public.validate_presupuesto_programa()
from public;


-- ============================================================================
-- 10. INMUTABILIDAD DE PRESUPUESTO_PARTIDAS
--
-- Durante el cierre, la cabecera todavía conserva estado='borrador' dentro
-- del BEFORE UPDATE. Por ello la actualización interna de snapshots supera
-- correctamente este control. Al terminar el cierre, cualquier cambio futuro
-- queda bloqueado.
-- ============================================================================

create function public.enforce_presupuesto_partidas_borrador()
returns trigger
language plpgsql
security definer
set search_path = ''
as $function$
begin
  if tg_op = 'INSERT' then
    perform public.assert_presupuesto_borrador(
      new.presupuesto_id,
      new.club_id,
      'insertar una partida'
    );
    return new;
  end if;

  if tg_op = 'DELETE' then
    perform public.assert_presupuesto_borrador(
      old.presupuesto_id,
      old.club_id,
      'eliminar una partida'
    );
    return old;
  end if;

  perform public.assert_presupuesto_borrador(
    old.presupuesto_id,
    old.club_id,
    'modificar la partida de origen'
  );

  perform public.assert_presupuesto_borrador(
    new.presupuesto_id,
    new.club_id,
    'modificar la partida de destino'
  );

  return new;
end;
$function$;

revoke all
on function public.enforce_presupuesto_partidas_borrador()
from public;


-- ============================================================================
-- 11. VALIDACIÓN DEL CONCEPTO DE CADA PARTIDA
-- ============================================================================

create function public.validate_presupuesto_partida()
returns trigger
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_tipo_programa text;
  v_concepto public.conceptos%rowtype;
  v_es_valido boolean;
begin
  select p.tipo_programa
  into v_tipo_programa
  from public.presupuestos as p
  where p.id_presupuesto = new.presupuesto_id
    and p.club_id = new.club_id;

  if not found then
    raise exception
      'No existe el presupuesto % en el club indicado.',
      new.presupuesto_id;
  end if;

  select c.*
  into v_concepto
  from public.conceptos as c
  where c.id_concepto = new.concepto_id
    and c.club_id = new.club_id;

  if not found then
    raise exception
      'El concepto % no existe o no pertenece al club del presupuesto.',
      new.concepto_id;
  end if;

  v_es_valido :=
    case v_tipo_programa
      when 'clubes' then v_concepto.valido_clubes
      when 'eventos' then v_concepto.valido_eventos
      when 'eedd_ctd_discapacidad'
        then v_concepto.valido_eedd_ctd_discapacidad
      else false
    end;

  if v_es_valido is not true then
    raise exception
      'El concepto % no es válido para el tipo de programa %.',
      new.concepto_id,
      v_tipo_programa;
  end if;

  if v_concepto.requisito_descripcion = 'obligatoria'
     and nullif(btrim(coalesce(new.descripcion, '')), '') is null
  then
    raise exception
      'El concepto % requiere una descripción obligatoria.',
      new.concepto_id;
  end if;

  -- requisito_entidad_origen se aplica a la ejecución contable. Una partida
  -- presupuestaria todavía no representa un pago, cobro o entidad concreta.

  new.updated_at := now();
  return new;
end;
$function$;

revoke all
on function public.validate_presupuesto_partida()
from public;


-- ============================================================================
-- 12. VALIDACIÓN DE CABECERA, SNAPSHOT Y CIERRE
--
-- El snapshot se ejecuta dentro del BEFORE UPDATE que procesa la transición
-- borrador -> cerrado. En ese momento la fila almacenada todavía es borrador,
-- por lo que los triggers de hijos permiten la actualización interna.
--
-- Si el snapshot, el equilibrio o cualquier otra comprobación falla, la
-- excepción revierte tanto la cabecera como todas las partidas actualizadas.
-- ============================================================================

create function public.validate_presupuesto_header()
returns trigger
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_total_gastos numeric(14, 2);
  v_total_ingresos numeric(14, 2);
  v_programas_incompatibles bigint;
  v_conceptos_incompatibles bigint;
  v_total_partidas bigint;
  v_partidas_snapshot bigint;
begin
  -- Una cabecera cerrada no admite UPDATE ni DELETE.
  if tg_op in ('UPDATE', 'DELETE') and old.estado = 'cerrado' then
    raise exception
      'El presupuesto % está cerrado y es inmutable.',
      old.id_presupuesto;
  end if;

  if tg_op = 'DELETE' then
    return old;
  end if;

  -- El club propietario es inmutable después de crear el presupuesto.
  if tg_op = 'UPDATE' and new.club_id <> old.club_id then
    raise exception
      'No se puede cambiar el club de un presupuesto existente.';
  end if;

  if tg_op = 'UPDATE' then
    -- Si cambia el tipo o el intervalo de años, todos los programas ya
    -- relacionados deben seguir siendo compatibles.
    if new.tipo_programa is distinct from old.tipo_programa
       or new.anio_inicio is distinct from old.anio_inicio
       or new.anio_fin is distinct from old.anio_fin
    then
      select count(*)
      into v_programas_incompatibles
      from public.presupuesto_programas as pp
      join public.programas as pr
        on pr.id_programa = pp.programa_id
       and pr.club_id = pp.club_id
      where pp.presupuesto_id = new.id_presupuesto
        and (
          pr.tipo_programa is distinct from new.tipo_programa
          or pr.anio is null
          or pr.anio < new.anio_inicio
          or pr.anio > new.anio_fin
        );

      if v_programas_incompatibles > 0 then
        raise exception
          'No puede cambiarse la cabecera: % programa(s) quedarían fuera del tipo o periodo del presupuesto.',
          v_programas_incompatibles;
      end if;
    end if;

    -- El cambio de familia funcional también revalida todos los conceptos.
    if new.tipo_programa is distinct from old.tipo_programa then
      select count(*)
      into v_conceptos_incompatibles
      from public.presupuesto_partidas as pp
      join public.conceptos as c
        on c.id_concepto = pp.concepto_id
       and c.club_id = pp.club_id
      where pp.presupuesto_id = new.id_presupuesto
        and (
          case new.tipo_programa
            when 'clubes' then c.valido_clubes
            when 'eventos' then c.valido_eventos
            when 'eedd_ctd_discapacidad'
              then c.valido_eedd_ctd_discapacidad
            else false
          end
        ) is not true;

      if v_conceptos_incompatibles > 0 then
        raise exception
          'No puede cambiarse el tipo: % concepto(s) quedarían incompatibles.',
          v_conceptos_incompatibles;
      end if;
    end if;

    -- Una nueva subvención debe incluir todos los programas ya asociados.
    if new.subvencion_id is distinct from old.subvencion_id
       and new.subvencion_id is not null
       and exists (
         select 1
         from public.presupuesto_programas as pp
         where pp.presupuesto_id = new.id_presupuesto
           and not exists (
             select 1
             from public.subvencion_programas as sp
             where sp.subvencion_id = new.subvencion_id
               and sp.programa_id = pp.programa_id
               and sp.club_id = new.club_id
           )
       )
    then
      raise exception
        'La nueva subvención no incluye todos los programas del presupuesto.';
    end if;
  end if;

  -- No se puede insertar una cabecera ya cerrada porque todavía no puede
  -- contener programas ni partidas.
  if tg_op = 'INSERT' and new.estado = 'cerrado' then
    raise exception
      'Un presupuesto debe crearse como borrador antes de poder cerrarse.';
  end if;

  if tg_op = 'UPDATE'
     and old.estado = 'borrador'
     and new.estado = 'cerrado'
  then
    if not exists (
      select 1
      from public.presupuesto_programas as pp
      where pp.presupuesto_id = new.id_presupuesto
    ) then
      raise exception
        'No puede cerrarse el presupuesto: no contiene programas contables.';
    end if;

    select count(*)
    into v_total_partidas
    from public.presupuesto_partidas as pp
    where pp.presupuesto_id = new.id_presupuesto;

    if v_total_partidas = 0 then
      raise exception
        'No puede cerrarse el presupuesto: no contiene partidas.';
    end if;

    -- Revalida todos los programas en el instante exacto del cierre.
    select count(*)
    into v_programas_incompatibles
    from public.presupuesto_programas as pp
    join public.programas as pr
      on pr.id_programa = pp.programa_id
     and pr.club_id = pp.club_id
    where pp.presupuesto_id = new.id_presupuesto
      and (
        pr.tipo_programa is distinct from new.tipo_programa
        or pr.anio is null
        or pr.anio < new.anio_inicio
        or pr.anio > new.anio_fin
      );

    if v_programas_incompatibles > 0 then
      raise exception
        'No puede cerrarse el presupuesto: % programa(s) son incompatibles.',
        v_programas_incompatibles;
    end if;

    -- Revalida los flags de los conceptos antes de congelar el catálogo.
    select count(*)
    into v_conceptos_incompatibles
    from public.presupuesto_partidas as pp
    join public.conceptos as c
      on c.id_concepto = pp.concepto_id
     and c.club_id = pp.club_id
    where pp.presupuesto_id = new.id_presupuesto
      and (
        case new.tipo_programa
          when 'clubes' then c.valido_clubes
          when 'eventos' then c.valido_eventos
          when 'eedd_ctd_discapacidad'
            then c.valido_eedd_ctd_discapacidad
          else false
        end
      ) is not true;

    if v_conceptos_incompatibles > 0 then
      raise exception
        'No puede cerrarse el presupuesto: % concepto(s) son incompatibles.',
        v_conceptos_incompatibles;
    end if;

    -- Congela el catálogo vigente. El JOIN incluye club_id para mantener el
    -- aislamiento incluso dentro de esta operación SECURITY DEFINER.
    update public.presupuesto_partidas as pp
    set
      concepto_nombre_snapshot = c.concepto,
      naturaleza_snapshot = c.naturaleza,
      subvencionabilidad_snapshot = c.subvencionabilidad
    from public.conceptos as c
    where pp.presupuesto_id = new.id_presupuesto
      and pp.club_id = new.club_id
      and c.id_concepto = pp.concepto_id
      and c.club_id = pp.club_id;

    get diagnostics v_partidas_snapshot = row_count;

    -- Una diferencia de recuentos significa que al menos una partida no pudo
    -- resolver su concepto. Aunque las FKs también lo protegen, esta comprobación
    -- hace que el cierre falle de forma explícita y defensiva.
    if v_partidas_snapshot <> v_total_partidas then
      raise exception
        'No puede cerrarse el presupuesto: se obtuvieron snapshots para % de % partidas.',
        v_partidas_snapshot,
        v_total_partidas;
    end if;

    -- Garantía cruzada: una cabecera cerrada nunca se confirma si alguna
    -- partida carece de cualquiera de sus tres campos históricos.
    if exists (
      select 1
      from public.presupuesto_partidas as pp
      where pp.presupuesto_id = new.id_presupuesto
        and (
          pp.concepto_nombre_snapshot is null
          or pp.naturaleza_snapshot is null
          or pp.subvencionabilidad_snapshot is null
        )
    ) then
      raise exception
        'No puede cerrarse el presupuesto: existen partidas con snapshot incompleto.';
    end if;

    -- En un presupuesto vinculado a subvención se utiliza ya el snapshot que
    -- quedará congelado. "condicionada" se permite y se advertirá en la UI.
    if new.subvencion_id is not null
       and exists (
         select 1
         from public.presupuesto_partidas as pp
         where pp.presupuesto_id = new.id_presupuesto
           and pp.subvencionabilidad_snapshot = 'no_subvencionable'
       )
    then
      raise exception
        'No puede cerrarse el presupuesto: contiene conceptos no subvencionables.';
    end if;

    -- El equilibrio se calcula desde los snapshots recién creados. No se
    -- almacenan columnas de totales y futuras modificaciones del catálogo no
    -- alterarán la interpretación histórica del cierre.
    select
      coalesce(
        sum(pp.importe_presupuestado)
          filter (where pp.naturaleza_snapshot = 'gasto'),
        0
      ),
      coalesce(
        sum(pp.importe_presupuestado)
          filter (where pp.naturaleza_snapshot = 'ingreso'),
        0
      )
    into v_total_gastos, v_total_ingresos
    from public.presupuesto_partidas as pp
    where pp.presupuesto_id = new.id_presupuesto;

    if v_total_gastos <= 0
       or v_total_ingresos <= 0
       or v_total_gastos <> v_total_ingresos
    then
      raise exception
        'No puede cerrarse el presupuesto: total de gastos = %, total de ingresos = %. Ambos deben ser mayores que cero e iguales.',
        v_total_gastos,
        v_total_ingresos;
    end if;

    new.cerrado_at := now();
  else
    new.cerrado_at := null;
  end if;

  new.updated_at := now();
  return new;
end;
$function$;

revoke all
on function public.validate_presupuesto_header()
from public;


-- ============================================================================
-- 13. TRIGGERS
--
-- PostgreSQL ejecuta alfabéticamente los triggers del mismo tipo. Los prefijos
-- 10 y 20 hacen que la inmutabilidad se compruebe antes de la compatibilidad.
-- ============================================================================

create trigger presupuestos_validate_header
before insert or update or delete
on public.presupuestos
for each row
execute function public.validate_presupuesto_header();

create trigger presupuesto_programas_10_require_draft
before insert or update or delete
on public.presupuesto_programas
for each row
execute function public.enforce_presupuesto_programas_borrador();

create trigger presupuesto_programas_20_validate
before insert or update
on public.presupuesto_programas
for each row
execute function public.validate_presupuesto_programa();

create trigger presupuesto_partidas_10_require_draft
before insert or update or delete
on public.presupuesto_partidas
for each row
execute function public.enforce_presupuesto_partidas_borrador();

create trigger presupuesto_partidas_20_validate
before insert or update
on public.presupuesto_partidas
for each row
execute function public.validate_presupuesto_partida();


-- ============================================================================
-- 14. ROW LEVEL SECURITY
-- ============================================================================

alter table public.presupuestos enable row level security;
alter table public.presupuesto_programas enable row level security;
alter table public.presupuesto_partidas enable row level security;

create policy presupuestos_select_by_club
on public.presupuestos for select to authenticated
using (public.can_access_club(club_id));

create policy presupuestos_insert_by_club
on public.presupuestos for insert to authenticated
with check (public.can_edit_club(club_id));

create policy presupuestos_update_by_club
on public.presupuestos for update to authenticated
using (public.can_edit_club(club_id))
with check (public.can_edit_club(club_id));

create policy presupuestos_delete_by_club
on public.presupuestos for delete to authenticated
using (public.can_edit_club(club_id));

create policy presupuesto_programas_select_by_club
on public.presupuesto_programas for select to authenticated
using (public.can_access_club(club_id));

create policy presupuesto_programas_insert_by_club
on public.presupuesto_programas for insert to authenticated
with check (public.can_edit_club(club_id));

create policy presupuesto_programas_update_by_club
on public.presupuesto_programas for update to authenticated
using (public.can_edit_club(club_id))
with check (public.can_edit_club(club_id));

create policy presupuesto_programas_delete_by_club
on public.presupuesto_programas for delete to authenticated
using (public.can_edit_club(club_id));

create policy presupuesto_partidas_select_by_club
on public.presupuesto_partidas for select to authenticated
using (public.can_access_club(club_id));

create policy presupuesto_partidas_insert_by_club
on public.presupuesto_partidas for insert to authenticated
with check (public.can_edit_club(club_id));

create policy presupuesto_partidas_update_by_club
on public.presupuesto_partidas for update to authenticated
using (public.can_edit_club(club_id))
with check (public.can_edit_club(club_id));

create policy presupuesto_partidas_delete_by_club
on public.presupuesto_partidas for delete to authenticated
using (public.can_edit_club(club_id));


-- ============================================================================
-- 15. PRIVILEGIOS DE TABLAS Y SECUENCIAS
-- ============================================================================

revoke all on table
  public.presupuestos,
  public.presupuesto_programas,
  public.presupuesto_partidas
from anon;

grant select, insert, update, delete on table
  public.presupuestos,
  public.presupuesto_programas,
  public.presupuesto_partidas
to authenticated;

-- Los default privileges auditados ya conceden acceso a secuencias, pero los
-- grants explícitos evitan depender de configuración implícita de plataforma.
revoke all on sequence
  public.presupuestos_id_presupuesto_seq,
  public.presupuesto_programas_id_presupuesto_programa_seq,
  public.presupuesto_partidas_id_partida_seq
from anon;

grant usage, select on sequence
  public.presupuestos_id_presupuesto_seq,
  public.presupuesto_programas_id_presupuesto_programa_seq,
  public.presupuesto_partidas_id_partida_seq
to authenticated;


-- ============================================================================
-- 16. COMENTARIOS DE USO HISTÓRICO
-- ============================================================================

comment on column public.presupuesto_partidas.concepto_nombre_snapshot is
  'Nombre del concepto congelado al cerrar. Los informes cerrados deben usar este campo.';

comment on column public.presupuesto_partidas.naturaleza_snapshot is
  'Naturaleza gasto/ingreso congelada al cerrar. Los informes cerrados deben usar este campo.';

comment on column public.presupuesto_partidas.subvencionabilidad_snapshot is
  'Subvencionabilidad congelada al cerrar. Los informes cerrados deben usar este campo.';

comment on column public.presupuesto_partidas.concepto_id is
  'Referencia al catálogo actual conservada para comparar con contabilidad.concepto_id.';

commit;


-- ============================================================================
-- ROLLBACK MANUAL COMPLETO
--
-- Este bloque está comentado deliberadamente para que nunca se ejecute como
-- parte de la migración de subida. Para revertir, debe copiarse a una migración
-- de rollback independiente después de revisar que no haya datos que conservar.
--
-- begin;
--
-- drop table if exists public.presupuesto_partidas;
-- drop table if exists public.presupuesto_programas;
-- drop table if exists public.presupuestos;
--
-- drop function if exists public.validate_presupuesto_header();
-- drop function if exists public.validate_presupuesto_partida();
-- drop function if exists public.enforce_presupuesto_partidas_borrador();
-- drop function if exists public.validate_presupuesto_programa();
-- drop function if exists public.enforce_presupuesto_programas_borrador();
-- drop function if exists
--   public.assert_presupuesto_borrador(bigint, bigint, text);
--
-- alter table public.subvenciones
--   drop constraint if exists subvenciones_id_subvencion_club_id_key;
-- alter table public.conceptos
--   drop constraint if exists conceptos_id_concepto_club_id_key;
-- alter table public.programas
--   drop constraint if exists programas_id_programa_club_id_key;
--
-- commit;
-- ============================================================================
